export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const countries: Country[] = [
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "ES", name: "Espanha", flag: "🇪🇸" },
  { code: "FR", name: "França", flag: "🇫🇷" },
  { code: "DE", name: "Alemanha", flag: "🇩🇪" },
  { code: "IT", name: "Itália", flag: "🇮🇹" },
  { code: "GB", name: "Reino Unido", flag: "🇬🇧" },
  { code: "US", name: "Estados Unidos", flag: "🇺🇸" },
  { code: "BR", name: "Brasil", flag: "🇧🇷" },
  { code: "NL", name: "Países Baixos", flag: "🇳🇱" },
  { code: "BE", name: "Bélgica", flag: "🇧🇪" },
  { code: "CH", name: "Suíça", flag: "🇨🇭" },
  { code: "AT", name: "Áustria", flag: "🇦🇹" },
  { code: "SE", name: "Suécia", flag: "🇸🇪" },
  { code: "NO", name: "Noruega", flag: "🇳🇴" },
  { code: "DK", name: "Dinamarca", flag: "🇩🇰" },
  { code: "FI", name: "Finlândia", flag: "🇫🇮" },
  { code: "PL", name: "Polónia", flag: "🇵🇱" },
  { code: "CZ", name: "República Checa", flag: "🇨🇿" },
  { code: "HU", name: "Hungria", flag: "🇭🇺" },
  { code: "RO", name: "Roménia", flag: "🇷🇴" },
  { code: "GR", name: "Grécia", flag: "🇬🇷" },
  { code: "IE", name: "Irlanda", flag: "🇮🇪" },
  { code: "LU", name: "Luxemburgo", flag: "🇱🇺" },
  { code: "HR", name: "Croácia", flag: "🇭🇷" },
  { code: "SI", name: "Eslovénia", flag: "🇸🇮" },
  { code: "SK", name: "Eslováquia", flag: "🇸🇰" },
  { code: "BG", name: "Bulgária", flag: "🇧🇬" },
  { code: "EE", name: "Estónia", flag: "🇪🇪" },
  { code: "LV", name: "Letónia", flag: "🇱🇻" },
  { code: "LT", name: "Lituânia", flag: "🇱🇹" },
  { code: "MT", name: "Malta", flag: "🇲🇹" },
  { code: "CY", name: "Chipre", flag: "🇨🇾" },
  { code: "CA", name: "Canadá", flag: "🇨🇦" },
  { code: "MX", name: "México", flag: "🇲🇽" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "CO", name: "Colômbia", flag: "🇨🇴" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "UY", name: "Uruguai", flag: "🇺🇾" },
  { code: "EC", name: "Equador", flag: "🇪🇨" },
  { code: "BO", name: "Bolívia", flag: "🇧🇴" },
  { code: "PY", name: "Paraguai", flag: "🇵🇾" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "JP", name: "Japão", flag: "🇯🇵" },
  { code: "KR", name: "Coreia do Sul", flag: "🇰🇷" },
  { code: "IN", name: "Índia", flag: "🇮🇳" },
  { code: "AU", name: "Austrália", flag: "🇦🇺" },
  { code: "NZ", name: "Nova Zelândia", flag: "🇳🇿" },
  { code: "ZA", name: "África do Sul", flag: "🇿🇦" },
  { code: "EG", name: "Egito", flag: "🇪🇬" },
  { code: "MA", name: "Marrocos", flag: "🇲🇦" },
  { code: "TN", name: "Tunísia", flag: "🇹🇳" },
  { code: "DZ", name: "Argélia", flag: "🇩🇿" },
  { code: "AE", name: "Emirados Árabes Unidos", flag: "🇦🇪" },
  { code: "SA", name: "Arábia Saudita", flag: "🇸🇦" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "TR", name: "Turquia", flag: "🇹🇷" },
  { code: "RU", name: "Rússia", flag: "🇷🇺" },
  { code: "UA", name: "Ucrânia", flag: "🇺🇦" },
  { code: "BY", name: "Bielorrússia", flag: "🇧🇾" },
  { code: "KZ", name: "Cazaquistão", flag: "🇰🇿" },
  { code: "TH", name: "Tailândia", flag: "🇹🇭" },
  { code: "SG", name: "Singapura", flag: "🇸🇬" },
  { code: "MY", name: "Malásia", flag: "🇲🇾" },
  { code: "ID", name: "Indonésia", flag: "🇮🇩" },
  { code: "PH", name: "Filipinas", flag: "🇵🇭" },
  { code: "VN", name: "Vietname", flag: "🇻🇳" },
  { code: "PK", name: "Paquistão", flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "NG", name: "Nigéria", flag: "🇳🇬" },
  { code: "KE", name: "Quénia", flag: "🇰🇪" },
  { code: "GH", name: "Gana", flag: "🇬🇭" },
  { code: "ET", name: "Etiópia", flag: "🇪🇹" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "MZ", name: "Moçambique", flag: "🇲🇿" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻" },
  { code: "GW", name: "Guiné-Bissau", flag: "🇬🇼" },
  { code: "ST", name: "São Tomé e Príncipe", flag: "🇸🇹" },
  { code: "IS", name: "Islândia", flag: "🇮🇸" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "MC", name: "Mónaco", flag: "🇲🇨" },
  { code: "AD", name: "Andorra", flag: "🇦🇩" },
  { code: "SM", name: "San Marino", flag: "🇸🇲" },
  { code: "VA", name: "Vaticano", flag: "🇻🇦" },
  { code: "RS", name: "Sérvia", flag: "🇷🇸" },
  { code: "BA", name: "Bósnia e Herzegovina", flag: "🇧🇦" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪" },
  { code: "MK", name: "Macedónia do Norte", flag: "🇲🇰" },
  { code: "AL", name: "Albânia", flag: "🇦🇱" },
  { code: "XK", name: "Kosovo", flag: "🇽🇰" },
  { code: "MD", name: "Moldávia", flag: "🇲🇩" },
  { code: "GE", name: "Geórgia", flag: "🇬🇪" },
  { code: "AM", name: "Arménia", flag: "🇦🇲" },
  { code: "AZ", name: "Azerbaijão", flag: "🇦🇿" },
];
